name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
             pip install --user conan cmake
             export PATH=$PATH:/home/runner/.local/bin/conan
    - name: configure
      run: mkdir build && cd build && cmake -DENABLE_TESTING=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
