name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
           pwd
           sudo apt-get install -y clang libclang-dev
           export CC="gcc"
           export CXX="g++"
           pip3 install wheel setuptools
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           echo $PATH
           conan --version
           ls
           sudo ln -s ~/.local/bin/conan /usr/local/bin/conan
    - name: configure
      run: mkdir build && cd build && cmake -DENABLE_TESTING=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
